"""Initialize

Revision ID: 01ccb7662fde
Revises: 
Create Date: 2025-12-21 12:55:03.329850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01ccb7662fde'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.Unicode(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('member_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_groups')),
    sa.UniqueConstraint('group_name', name=op.f('uq_groups_group_name')),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment'))
    )
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions')),
    sa.UniqueConstraint('name', name=op.f('uq_permissions_name'))
    )
    op.create_table('users',
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('last_login_date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('security_code_date', sa.TIMESTAMP(timezone=True), server_default='2000-01-01 01:01', nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.Unicode(length=128), nullable=True),
    sa.Column('user_password', sa.Unicode(length=256), nullable=True),
    sa.Column('email', sa.Unicode(length=100), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('security_code', sa.Unicode(length=256), nullable=True),
    sa.Column('registered_date', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('user_name', name=op.f('uq_users_user_name')),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('coa',
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('code', sa.String(length=128), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('create_uid', sa.Integer(), nullable=True),
    sa.Column('update_uid', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['create_uid'], ['users.id'], name=op.f('fk_coa_create_uid_users'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['coa.id'], name=op.f('fk_coa_parent_id_coa'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['update_uid'], ['users.id'], name=op.f('fk_coa_update_uid_users'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coa')),
    sa.UniqueConstraint('code', name=op.f('uq_coa_code'))
    )
    op.create_table('external_identities',
    sa.Column('external_id', sa.Unicode(length=255), nullable=False),
    sa.Column('external_user_name', sa.Unicode(length=255), nullable=True),
    sa.Column('local_user_id', sa.Integer(), nullable=False),
    sa.Column('provider_name', sa.Unicode(length=50), nullable=False),
    sa.Column('access_token', sa.Unicode(length=512), nullable=True),
    sa.Column('alt_token', sa.Unicode(length=512), nullable=True),
    sa.Column('token_secret', sa.Unicode(length=512), nullable=True),
    sa.ForeignKeyConstraint(['local_user_id'], ['users.id'], name=op.f('fk_external_identities_local_user_id_users'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('external_id', 'local_user_id', 'provider_name', name='pk_external_identities'),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('groups_permissions',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('perm_name', sa.Unicode(length=64), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_groups_permissions_group_id_groups'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'perm_name', name='pk_groups_permissions'),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('invoice_category',
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('create_uid', sa.Integer(), nullable=True),
    sa.Column('update_uid', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['create_uid'], ['users.id'], name=op.f('fk_invoice_category_create_uid_users'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['update_uid'], ['users.id'], name=op.f('fk_invoice_category_update_uid_users'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice_category')),
    sa.UniqueConstraint('name', name=op.f('uq_invoice_category_name'))
    )
    op.create_table('product_category',
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('create_uid', sa.Integer(), nullable=True),
    sa.Column('update_uid', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['create_uid'], ['users.id'], name=op.f('fk_product_category_create_uid_users'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['update_uid'], ['users.id'], name=op.f('fk_product_category_update_uid_users'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_category')),
    sa.UniqueConstraint('name', name=op.f('uq_product_category_name'))
    )
    op.create_table('provinsi',
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('create_uid', sa.Integer(), nullable=True),
    sa.Column('update_uid', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['create_uid'], ['users.id'], name=op.f('fk_provinsi_create_uid_users'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['update_uid'], ['users.id'], name=op.f('fk_provinsi_update_uid_users'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provinsi'))
    )
    op.create_table('resources',
    sa.Column('resource_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('ordering', sa.Integer(), nullable=False),
    sa.Column('resource_name', sa.Unicode(length=100), nullable=False),
    sa.Column('resource_type', sa.Unicode(length=30), nullable=False),
    sa.Column('owner_group_id', sa.Integer(), nullable=True),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_group_id'], ['groups.id'], name=op.f('fk_resources_owner_group_id_groups'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_resources_owner_user_id_users'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['resources.resource_id'], name=op.f('fk_resources_parent_id_resources'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('resource_id', name=op.f('pk_resources')),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_resources_owner_group_id'), 'resources', ['owner_group_id'], unique=False)
    op.create_index(op.f('ix_resources_owner_user_id'), 'resources', ['owner_user_id'], unique=False)
    op.create_table('users_groups',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_users_groups_group_id_groups'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_users_groups_user_id_users'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'user_id', name=op.f('pk_users_groups')),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('users_permissions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('perm_name', sa.Unicode(length=64), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_users_permissions_user_id_users'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'perm_name', name='pk_users_permissions'),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('groups_resources_permissions',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('perm_name', sa.Unicode(length=50), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_groups_resources_permissions_group_id_groups'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.resource_id'], name=op.f('fk_groups_resources_permissions_resource_id_resources'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'resource_id', 'perm_name', name='pk_groups_resources_permissions '),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('kota',
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('provinsi_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('create_uid', sa.Integer(), nullable=True),
    sa.Column('update_uid', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['create_uid'], ['users.id'], name=op.f('fk_kota_create_uid_users'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provinsi_id'], ['provinsi.id'], name=op.f('fk_kota_provinsi_id_provinsi'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['update_uid'], ['users.id'], name=op.f('fk_kota_update_uid_users'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kota'))
    )
    op.create_table('product',
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('min_stock', sa.Integer(), nullable=True),
    sa.Column('selleable', sa.SmallInteger(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('create_uid', sa.Integer(), nullable=True),
    sa.Column('update_uid', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['product_category.id'], name=op.f('fk_product_category_id_product_category'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['create_uid'], ['users.id'], name=op.f('fk_product_create_uid_users'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['update_uid'], ['users.id'], name=op.f('fk_product_update_uid_users'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product'))
    )
    op.create_table('users_resources_permissions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('perm_name', sa.Unicode(length=64), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.resource_id'], name=op.f('fk_users_resources_permissions_resource_id_resources'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_users_resources_permissions_user_id_users'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'resource_id', 'perm_name', name='pk_users_resources_permissions '),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('kecamatan',
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('kota_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('create_uid', sa.Integer(), nullable=True),
    sa.Column('update_uid', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['create_uid'], ['users.id'], name=op.f('fk_kecamatan_create_uid_users'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['kota_id'], ['kota.id'], name=op.f('fk_kecamatan_kota_id_kota'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['update_uid'], ['users.id'], name=op.f('fk_kecamatan_update_uid_users'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kecamatan'))
    )
    op.create_table('product_items',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['product.id'], name=op.f('fk_product_items_item_id_product'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_product_items_product_id_product'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'item_id', name=op.f('pk_product_items'))
    )
    op.create_table('partner',
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('kode', sa.String(length=32), nullable=True),
    sa.Column('kelurahan', sa.String(length=64), nullable=True),
    sa.Column('addres_1', sa.String(length=64), nullable=True),
    sa.Column('addres_2', sa.String(length=64), nullable=True),
    sa.Column('is_vendor', sa.SmallInteger(), nullable=True),
    sa.Column('is_customer', sa.SmallInteger(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('provinsi_id', sa.Integer(), nullable=False),
    sa.Column('kota_id', sa.Integer(), nullable=False),
    sa.Column('kecamatan_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('create_uid', sa.Integer(), nullable=True),
    sa.Column('update_uid', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['create_uid'], ['users.id'], name=op.f('fk_partner_create_uid_users'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['kecamatan_id'], ['kecamatan.id'], name=op.f('fk_partner_kecamatan_id_kecamatan'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['kota_id'], ['kota.id'], name=op.f('fk_partner_kota_id_kota'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['provinsi_id'], ['provinsi.id'], name=op.f('fk_partner_provinsi_id_provinsi'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['update_uid'], ['users.id'], name=op.f('fk_partner_update_uid_users'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_partner'))
    )
    op.create_table('invoices',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('code', sa.String(length=128), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('est_delivery', sa.DateTime(), nullable=True),
    sa.Column('invoice_date', sa.DateTime(), nullable=True),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('create_uid', sa.Integer(), nullable=True),
    sa.Column('update_uid', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['invoice_category.id'], name=op.f('fk_invoices_category_id_invoice_category'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['create_uid'], ['users.id'], name=op.f('fk_invoices_create_uid_users'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['partner_id'], ['partner.id'], name=op.f('fk_invoices_partner_id_partner'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['update_uid'], ['users.id'], name=op.f('fk_invoices_update_uid_users'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoices'))
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('code', sa.String(length=128), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('est_delivery', sa.DateTime(), nullable=True),
    sa.Column('order_date', sa.DateTime(), nullable=True),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('create_uid', sa.Integer(), nullable=True),
    sa.Column('update_uid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['create_uid'], ['users.id'], name=op.f('fk_orders_create_uid_users'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['partner_id'], ['partner.id'], name=op.f('fk_orders_partner_id_partner'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['update_uid'], ['users.id'], name=op.f('fk_orders_update_uid_users'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders'))
    )
    op.create_table('order_items',
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('invoiced', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['orders.id'], name=op.f('fk_order_items_invoice_id_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_order_items_product_id_product'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_items')),
    sa.UniqueConstraint('invoice_id', 'product_id', name=op.f('uq_order_items_invoice_id'))
    )
    op.create_table('invoice_items',
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('order_item_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_invoice_items_invoice_id_invoices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['order_items.id'], name=op.f('fk_invoice_items_order_id_order_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], name=op.f('fk_invoice_items_order_item_id_order_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_invoice_items_product_id_product'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('invoice_id', 'product_id', name=op.f('pk_invoice_items'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoice_items')
    op.drop_table('order_items')
    op.drop_table('orders')
    op.drop_table('invoices')
    op.drop_table('partner')
    op.drop_table('product_items')
    op.drop_table('kecamatan')
    op.drop_table('users_resources_permissions')
    op.drop_table('product')
    op.drop_table('kota')
    op.drop_table('groups_resources_permissions')
    op.drop_table('users_permissions')
    op.drop_table('users_groups')
    op.drop_index(op.f('ix_resources_owner_user_id'), table_name='resources')
    op.drop_index(op.f('ix_resources_owner_group_id'), table_name='resources')
    op.drop_table('resources')
    op.drop_table('provinsi')
    op.drop_table('product_category')
    op.drop_table('invoice_category')
    op.drop_table('groups_permissions')
    op.drop_table('external_identities')
    op.drop_table('coa')
    op.drop_table('users')
    op.drop_table('permissions')
    op.drop_table('payment')
    op.drop_table('groups')
    # ### end Alembic commands ###
