"""Tambah tabel product

Revision ID: 1106fd114932
Revises: 31a537f9c80e
Create Date: 2025-11-16 15:21:36.332917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1106fd114932'
down_revision: Union[str, Sequence[str], None] = '31a537f9c80e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_category',
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('create_uid', sa.Integer(), nullable=False),
    sa.Column('update_uid', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['create_uid'], ['users.id'], name=op.f('fk_product_category_create_uid_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['update_uid'], ['users.id'], name=op.f('fk_product_category_update_uid_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_category')),
    sa.UniqueConstraint('name', name=op.f('uq_product_category_name'))
    )
    op.create_table('product',
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('min_stock', sa.Integer(), nullable=True),
    sa.Column('selleable', sa.SmallInteger(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('create_uid', sa.Integer(), nullable=False),
    sa.Column('update_uid', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['product_category.id'], name=op.f('fk_product_category_id_product_category'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['create_uid'], ['users.id'], name=op.f('fk_product_create_uid_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['update_uid'], ['users.id'], name=op.f('fk_product_update_uid_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product'))
    )
    op.create_table('product_items',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['product.id'], name=op.f('fk_product_items_item_id_product'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_product_items_product_id_product'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'item_id', name=op.f('pk_product_items'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_items')
    op.drop_table('product')
    op.drop_table('product_category')
    # ### end Alembic commands ###
