"""Change default to standard for product

Revision ID: 3ffdf2e6c1f0
Revises: 1106fd114932
Create Date: 2025-11-16 15:30:42.609797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3ffdf2e6c1f0'
down_revision: Union[str, Sequence[str], None] = '1106fd114932'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_groups_create_uid_users'), 'groups', type_='foreignkey')
    op.drop_constraint(op.f('fk_groups_update_uid_users'), 'groups', type_='foreignkey')
    op.drop_column('groups', 'created')
    op.drop_column('groups', 'update_uid')
    op.drop_column('groups', 'status')
    op.drop_column('groups', 'create_uid')
    op.drop_column('groups', 'updated')
    op.drop_constraint(op.f('fk_groups_permissions_create_uid_users'), 'groups_permissions', type_='foreignkey')
    op.drop_constraint(op.f('fk_groups_permissions_update_uid_users'), 'groups_permissions', type_='foreignkey')
    op.drop_column('groups_permissions', 'created')
    op.drop_column('groups_permissions', 'update_uid')
    op.drop_column('groups_permissions', 'status')
    op.drop_column('groups_permissions', 'create_uid')
    op.drop_column('groups_permissions', 'updated')
    op.drop_constraint(op.f('fk_users_create_uid_users'), 'users', type_='foreignkey')
    op.drop_constraint(op.f('fk_users_update_uid_users'), 'users', type_='foreignkey')
    op.drop_column('users', 'create_uid')
    op.drop_column('users', 'created')
    op.drop_column('users', 'update_uid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('update_uid', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('create_uid', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('fk_users_update_uid_users'), 'users', 'users', ['update_uid'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_users_create_uid_users'), 'users', 'users', ['create_uid'], ['id'], ondelete='RESTRICT')
    op.add_column('groups_permissions', sa.Column('updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('groups_permissions', sa.Column('create_uid', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('groups_permissions', sa.Column('status', sa.SMALLINT(), autoincrement=False, nullable=True))
    op.add_column('groups_permissions', sa.Column('update_uid', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('groups_permissions', sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_groups_permissions_update_uid_users'), 'groups_permissions', 'users', ['update_uid'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_groups_permissions_create_uid_users'), 'groups_permissions', 'users', ['create_uid'], ['id'], ondelete='RESTRICT')
    op.add_column('groups', sa.Column('updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('groups', sa.Column('create_uid', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('groups', sa.Column('status', sa.SMALLINT(), autoincrement=False, nullable=True))
    op.add_column('groups', sa.Column('update_uid', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('groups', sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_groups_update_uid_users'), 'groups', 'users', ['update_uid'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_groups_create_uid_users'), 'groups', 'users', ['create_uid'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###
