"""Penambahan Accounting

Revision ID: 59ba13abd48d
Revises: 9ba048e11e8d
Create Date: 2025-12-08 11:45:01.535448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '59ba13abd48d'
down_revision: Union[str, Sequence[str], None] = '9ba048e11e8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice_category',
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('create_uid', sa.Integer(), nullable=True),
    sa.Column('update_uid', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['create_uid'], ['users.id'], name=op.f('fk_invoice_category_create_uid_users'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['update_uid'], ['users.id'], name=op.f('fk_invoice_category_update_uid_users'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice_category')),
    sa.UniqueConstraint('name', name=op.f('uq_invoice_category_name'))
    )

    op.add_column('invoices', sa.Column(
        'category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_invoices_category_id_invoice_category'), 'invoices', 'invoice_category', ['category_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')

# ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('invoice_items', 'order_id')
    # op.drop_column('invoice_items', 'order_item_id')
    op.drop_constraint(op.f('fk_invoices_category_id_invoice_category'), 'invoices', type_='foreignkey')
    op.drop_column('invoices', 'category_id')
    op.drop_table('invoice_category')
    # ### end Alembic commands ###
