"""Tambah table wilayah2

Revision ID: 6c95f8dc93bc
Revises: b3c38743f5c3
Create Date: 2025-11-16 15:58:41.731811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c95f8dc93bc'
down_revision: Union[str, Sequence[str], None] = 'b3c38743f5c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
