"""tambah payment

Revision ID: 7466d47338a9
Revises: 01ccb7662fde
Create Date: 2025-12-21 17:47:43.681375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7466d47338a9'
down_revision: Union[str, Sequence[str], None] = '01ccb7662fde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_items',
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_payment_items_invoice_id_invoices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], name=op.f('fk_payment_items_payment_id_payment'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('payment_id', 'invoice_id', name=op.f('pk_payment_items'))
    )
    op.add_column('payment', sa.Column('partner_id', sa.Integer(), nullable=False))
    op.add_column('payment', sa.Column('status', sa.SmallInteger(), nullable=True))
    op.add_column('payment', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('payment', sa.Column('updated', sa.DateTime(), nullable=True))
    op.add_column('payment', sa.Column('create_uid', sa.Integer(), nullable=True))
    op.add_column('payment', sa.Column('update_uid', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_payment_partner_id_partner'), 'payment', 'partner', ['partner_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_payment_create_uid_users'), 'payment', 'users', ['create_uid'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_payment_update_uid_users'), 'payment', 'users', ['update_uid'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('payment', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_payment_update_uid_users'), 'payment', type_='foreignkey')
    op.drop_constraint(op.f('fk_payment_create_uid_users'), 'payment', type_='foreignkey')
    op.drop_constraint(op.f('fk_payment_partner_id_partner'), 'payment', type_='foreignkey')
    op.drop_column('payment', 'update_uid')
    op.drop_column('payment', 'create_uid')
    op.drop_column('payment', 'updated')
    op.drop_column('payment', 'created')
    op.drop_column('payment', 'status')
    op.drop_column('payment', 'partner_id')
    op.drop_table('payment_items')
    # ### end Alembic commands ###
