"""Update Models

Revision ID: 7f044e9c3c0d
Revises: 7968ae6fa1dd
Create Date: 2025-11-16 11:34:45.421583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f044e9c3c0d'
down_revision: Union[str, Sequence[str], None] = '7968ae6fa1dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups_permissions', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups_permissions', 'id')
    # ### end Alembic commands ###
