"""Tambah Models Partner

Revision ID: ab3c78ad8932
Revises: e4f683a52e88
Create Date: 2025-11-16 20:25:13.019338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ab3c78ad8932'
down_revision: Union[str, Sequence[str], None] = 'e4f683a52e88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partner',
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('kode', sa.String(length=32), nullable=True),
    sa.Column('kelurahan', sa.String(length=64), nullable=True),
    sa.Column('addres_1', sa.String(length=64), nullable=True),
    sa.Column('addres_2', sa.String(length=64), nullable=True),
    sa.Column('is_vendor', sa.SmallInteger(), nullable=True),
    sa.Column('is_customer', sa.SmallInteger(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('provinsi_id', sa.Integer(), nullable=False),
    sa.Column('kota_id', sa.Integer(), nullable=False),
    sa.Column('kecamatan_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('create_uid', sa.Integer(), nullable=False),
    sa.Column('update_uid', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['create_uid'], ['users.id'], name=op.f('fk_partner_create_uid_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['kecamatan_id'], ['kecamatan.id'], name=op.f('fk_partner_kecamatan_id_kecamatan'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['kota_id'], ['kota.id'], name=op.f('fk_partner_kota_id_kota'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['provinsi_id'], ['provinsi.id'], name=op.f('fk_partner_provinsi_id_provinsi'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['update_uid'], ['users.id'], name=op.f('fk_partner_update_uid_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_partner'))
    )
    op.drop_table('beaker_cache')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beaker_cache',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('namespace', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('accessed', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('beaker_cache_pkey')),
    sa.UniqueConstraint('namespace', name=op.f('beaker_cache_namespace_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('partner')
    # ### end Alembic commands ###
