"""Tambah Models Invoice

Revision ID: bd39e1834c1b
Revises: ab3c78ad8932
Create Date: 2025-11-16 20:26:53.680961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd39e1834c1b'
down_revision: Union[str, Sequence[str], None] = 'ab3c78ad8932'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('code', sa.String(length=128), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('est_delivery', sa.DateTime(), nullable=True),
    sa.Column('invoice_date', sa.DateTime(), nullable=True),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('create_uid', sa.Integer(), nullable=False),
    sa.Column('update_uid', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['create_uid'], ['users.id'], name=op.f('fk_invoices_create_uid_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['partner_id'], ['partner.id'], name=op.f('fk_invoices_partner_id_partner'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['update_uid'], ['users.id'], name=op.f('fk_invoices_update_uid_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoices'))
    )
    op.create_table('invoice_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('invoice_det_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_det_id'], ['invoices.id'], name=op.f('fk_invoice_items_invoice_det_id_invoices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_invoice_items_invoice_id_invoices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_invoice_items_product_id_product'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice_items'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoice_items')
    op.drop_table('invoices')
    # ### end Alembic commands ###
