"""add coa

Revision ID: c6540079bbee
Revises: fbaac20d4155
Create Date: 2025-12-21 12:07:23.831129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6540079bbee'
down_revision: Union[str, Sequence[str], None] = 'fbaac20d4155'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coa',
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('code', sa.String(length=128), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('create_uid', sa.Integer(), nullable=True),
    sa.Column('update_uid', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['create_uid'], ['users.id'], name=op.f('fk_coa_create_uid_users'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['coa.id'], name=op.f('fk_coa_parent_id_coa'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['update_uid'], ['users.id'], name=op.f('fk_coa_update_uid_users'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coa')),
    sa.UniqueConstraint('code', name=op.f('uq_coa_code'))
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('code', sa.String(length=128), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('est_delivery', sa.DateTime(), nullable=True),
    sa.Column('order_date', sa.DateTime(), nullable=True),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('create_uid', sa.Integer(), nullable=True),
    sa.Column('update_uid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['create_uid'], ['users.id'], name=op.f('fk_orders_create_uid_users'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['partner_id'], ['partner.id'], name=op.f('fk_orders_partner_id_partner'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['update_uid'], ['users.id'], name=op.f('fk_orders_update_uid_users'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders'))
    )
    op.create_table('order_items',
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('invoiced', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['orders.id'], name=op.f('fk_order_items_invoice_id_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_order_items_product_id_product'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_items')),
    sa.UniqueConstraint('invoice_id', 'product_id', name=op.f('uq_order_items_invoice_id'))
    )
    op.drop_column('groups_permissions', 'id')
    op.add_column('invoice_items', sa.Column('order_item_id', sa.Integer(), nullable=True))
    op.add_column('invoice_items', sa.Column('order_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('fk_invoice_items_invoice_det_id_invoices'), 'invoice_items', type_='foreignkey')
    op.create_foreign_key(op.f('fk_invoice_items_order_id_order_items'), 'invoice_items', 'order_items', ['order_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_invoice_items_order_item_id_order_items'), 'invoice_items', 'order_items', ['order_item_id'], ['id'], ondelete='CASCADE')
    op.drop_column('invoice_items', 'status')
    op.drop_column('invoice_items', 'invoice_det_id')
    op.drop_column('invoice_items', 'id')
    op.alter_column('invoices', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('invoices', 'create_uid',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('fk_invoices_category_id_invoice_category'), 'invoices', type_='foreignkey')
    op.drop_constraint(op.f('fk_invoices_create_uid_users'), 'invoices', type_='foreignkey')
    op.drop_constraint(op.f('fk_invoices_update_uid_users'), 'invoices', type_='foreignkey')
    op.create_foreign_key(op.f('fk_invoices_update_uid_users'), 'invoices', 'users', ['update_uid'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_invoices_category_id_invoice_category'), 'invoices', 'invoice_category', ['category_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_invoices_create_uid_users'), 'invoices', 'users', ['create_uid'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('kecamatan', 'create_uid',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('fk_kecamatan_update_uid_users'), 'kecamatan', type_='foreignkey')
    op.drop_constraint(op.f('fk_kecamatan_create_uid_users'), 'kecamatan', type_='foreignkey')
    op.create_foreign_key(op.f('fk_kecamatan_create_uid_users'), 'kecamatan', 'users', ['create_uid'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_kecamatan_update_uid_users'), 'kecamatan', 'users', ['update_uid'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('kota', 'create_uid',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('fk_kota_create_uid_users'), 'kota', type_='foreignkey')
    op.drop_constraint(op.f('fk_kota_update_uid_users'), 'kota', type_='foreignkey')
    op.create_foreign_key(op.f('fk_kota_create_uid_users'), 'kota', 'users', ['create_uid'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_kota_update_uid_users'), 'kota', 'users', ['update_uid'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('partner', 'create_uid',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('fk_partner_create_uid_users'), 'partner', type_='foreignkey')
    op.drop_constraint(op.f('fk_partner_update_uid_users'), 'partner', type_='foreignkey')
    op.create_foreign_key(op.f('fk_partner_create_uid_users'), 'partner', 'users', ['create_uid'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_partner_update_uid_users'), 'partner', 'users', ['update_uid'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('product', 'create_uid',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('fk_product_create_uid_users'), 'product', type_='foreignkey')
    op.drop_constraint(op.f('fk_product_update_uid_users'), 'product', type_='foreignkey')
    op.create_foreign_key(op.f('fk_product_create_uid_users'), 'product', 'users', ['create_uid'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_product_update_uid_users'), 'product', 'users', ['update_uid'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('product_category', 'create_uid',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('fk_product_category_update_uid_users'), 'product_category', type_='foreignkey')
    op.drop_constraint(op.f('fk_product_category_create_uid_users'), 'product_category', type_='foreignkey')
    op.create_foreign_key(op.f('fk_product_category_create_uid_users'), 'product_category', 'users', ['create_uid'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_product_category_update_uid_users'), 'product_category', 'users', ['update_uid'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('provinsi', 'create_uid',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('fk_provinsi_update_uid_users'), 'provinsi', type_='foreignkey')
    op.drop_constraint(op.f('fk_provinsi_create_uid_users'), 'provinsi', type_='foreignkey')
    op.create_foreign_key(op.f('fk_provinsi_update_uid_users'), 'provinsi', 'users', ['update_uid'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_provinsi_create_uid_users'), 'provinsi', 'users', ['create_uid'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_provinsi_create_uid_users'), 'provinsi', type_='foreignkey')
    op.drop_constraint(op.f('fk_provinsi_update_uid_users'), 'provinsi', type_='foreignkey')
    op.create_foreign_key(op.f('fk_provinsi_create_uid_users'), 'provinsi', 'users', ['create_uid'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_provinsi_update_uid_users'), 'provinsi', 'users', ['update_uid'], ['id'], ondelete='RESTRICT')
    op.alter_column('provinsi', 'create_uid',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('fk_product_category_update_uid_users'), 'product_category', type_='foreignkey')
    op.drop_constraint(op.f('fk_product_category_create_uid_users'), 'product_category', type_='foreignkey')
    op.create_foreign_key(op.f('fk_product_category_create_uid_users'), 'product_category', 'users', ['create_uid'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_product_category_update_uid_users'), 'product_category', 'users', ['update_uid'], ['id'], ondelete='RESTRICT')
    op.alter_column('product_category', 'create_uid',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('fk_product_update_uid_users'), 'product', type_='foreignkey')
    op.drop_constraint(op.f('fk_product_create_uid_users'), 'product', type_='foreignkey')
    op.create_foreign_key(op.f('fk_product_update_uid_users'), 'product', 'users', ['update_uid'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_product_create_uid_users'), 'product', 'users', ['create_uid'], ['id'], ondelete='RESTRICT')
    op.alter_column('product', 'create_uid',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('fk_partner_update_uid_users'), 'partner', type_='foreignkey')
    op.drop_constraint(op.f('fk_partner_create_uid_users'), 'partner', type_='foreignkey')
    op.create_foreign_key(op.f('fk_partner_update_uid_users'), 'partner', 'users', ['update_uid'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_partner_create_uid_users'), 'partner', 'users', ['create_uid'], ['id'], ondelete='RESTRICT')
    op.alter_column('partner', 'create_uid',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('fk_kota_update_uid_users'), 'kota', type_='foreignkey')
    op.drop_constraint(op.f('fk_kota_create_uid_users'), 'kota', type_='foreignkey')
    op.create_foreign_key(op.f('fk_kota_update_uid_users'), 'kota', 'users', ['update_uid'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_kota_create_uid_users'), 'kota', 'users', ['create_uid'], ['id'], ondelete='RESTRICT')
    op.alter_column('kota', 'create_uid',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('fk_kecamatan_update_uid_users'), 'kecamatan', type_='foreignkey')
    op.drop_constraint(op.f('fk_kecamatan_create_uid_users'), 'kecamatan', type_='foreignkey')
    op.create_foreign_key(op.f('fk_kecamatan_create_uid_users'), 'kecamatan', 'users', ['create_uid'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_kecamatan_update_uid_users'), 'kecamatan', 'users', ['update_uid'], ['id'], ondelete='RESTRICT')
    op.alter_column('kecamatan', 'create_uid',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('fk_invoices_create_uid_users'), 'invoices', type_='foreignkey')
    op.drop_constraint(op.f('fk_invoices_category_id_invoice_category'), 'invoices', type_='foreignkey')
    op.drop_constraint(op.f('fk_invoices_update_uid_users'), 'invoices', type_='foreignkey')
    op.create_foreign_key(op.f('fk_invoices_update_uid_users'), 'invoices', 'users', ['update_uid'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_invoices_create_uid_users'), 'invoices', 'users', ['create_uid'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_invoices_category_id_invoice_category'), 'invoices', 'invoice_category', ['category_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.alter_column('invoices', 'create_uid',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('invoices', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('invoice_items', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('invoice_items', sa.Column('invoice_det_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('invoice_items', sa.Column('status', sa.SMALLINT(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_invoice_items_order_item_id_order_items'), 'invoice_items', type_='foreignkey')
    op.drop_constraint(op.f('fk_invoice_items_order_id_order_items'), 'invoice_items', type_='foreignkey')
    op.create_foreign_key(op.f('fk_invoice_items_invoice_det_id_invoices'), 'invoice_items', 'invoices', ['invoice_det_id'], ['id'], ondelete='CASCADE')
    op.drop_column('invoice_items', 'order_id')
    op.drop_column('invoice_items', 'order_item_id')
    op.add_column('groups_permissions', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_table('order_items')
    op.drop_table('orders')
    op.drop_table('coa')
    # ### end Alembic commands ###
