"""Add Table Wilayah

Revision ID: e4f683a52e88
Revises: 3ffdf2e6c1f0
Create Date: 2025-11-16 16:44:59.276896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e4f683a52e88'
down_revision: Union[str, Sequence[str], None] = '3ffdf2e6c1f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provinsi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('create_uid', sa.Integer(), nullable=False),
    sa.Column('update_uid', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['create_uid'], ['users.id'], name=op.f('fk_provinsi_create_uid_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['update_uid'], ['users.id'], name=op.f('fk_provinsi_update_uid_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provinsi'))
    )
    op.create_table('kota',
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('provinsi_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('create_uid', sa.Integer(), nullable=False),
    sa.Column('update_uid', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['create_uid'], ['users.id'], name=op.f('fk_kota_create_uid_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['provinsi_id'], ['provinsi.id'], name=op.f('fk_kota_provinsi_id_provinsi'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['update_uid'], ['users.id'], name=op.f('fk_kota_update_uid_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kota'))
    )
    op.create_table('kecamatan',
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('kota_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('create_uid', sa.Integer(), nullable=False),
    sa.Column('update_uid', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['create_uid'], ['users.id'], name=op.f('fk_kecamatan_create_uid_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['kota_id'], ['kota.id'], name=op.f('fk_kecamatan_kota_id_kota'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['update_uid'], ['users.id'], name=op.f('fk_kecamatan_update_uid_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kecamatan'))
    )
    op.drop_table('beaker_cache')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beaker_cache',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('namespace', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('accessed', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('beaker_cache_pkey')),
    sa.UniqueConstraint('namespace', name=op.f('beaker_cache_namespace_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('kecamatan')
    op.drop_table('kota')
    op.drop_table('provinsi')
    # ### end Alembic commands ###
