"""tambah kolom est_delivery

Revision ID: fbb71c5d5fdf
Revises: 7e43dea3d411
Create Date: 2025-12-21 11:46:51.243133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbb71c5d5fdf'
down_revision: Union[str, Sequence[str], None] = '7e43dea3d411'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
